name: ebrick
version: '3.8'

services:
  redis-stack:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - "6379:6379" # Redis server port
      - "8001:8001" # RedisInsight (GUI) port
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432" # PostgreSQL server port
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  nats:
    container_name: nats-server
    image: nats:2.10.18
    command: '-js'
    ports:
      - '4222:4222'
    environment:
      NATS_ADDRESS: nats://nats:4222

  nats-ui:
    container_name: nats-ui
    image: ghcr.io/nats-nui/nui:0.4
    ports:
      - '31311:31311'
volumes:
  nats_data:
